version: "3"
services:
  ui:
    build:
      context: ./ui
    ports:
      - 5173:5173

  nginx:
    image: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8080:80"
    depends_on:
      - ui
      - microservice-1
      - microservice-2

  microservice-1:
    build:
      context: ./microservice-1
    ports:
      - "3001:3001"

  microservice-2:
    build:
      context: ./microservice-2
    ports:
      - "3002:3002"
